export AWS_ACCESS_KEY_ID={{ lookup('env','AWS_ACCESS_KEY_ID') }}
export AWS_SECRET_ACCESS_KEY={{ lookup('env','AWS_SECRET_ACCESS_KEY') }}
export DO_API_TOKEN={{ lookup('env','DO_API_TOKEN') }}
export DME_AKEY={{ lookup('env','DME_AKEY') }}
export DME_SKEY={{ lookup('env','DME_SKEY') }}
source ~/venv/bin/activate